import { Hind_Siliguri, Poppins } from "next/font/google";
import "./globals.css";
import { Provider } from "react-redux";
import StoreProvider from "@/redux/StoreProvider";

const hindSiliguri = Hind_Siliguri({
    variable: "--font-hind-siliguri",
    subsets: ["bengali", "latin"],
    weight: ["300", "400", "500", "600", "700"],
});

const poppins = Poppins({
    variable: "--font-poppins",
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
    title: "DIPLOMA360",
    description: "Generated by create next app",
    icons: {
        icon: "/icon.png",
    },
};

export default function RootLayout({ children }) {
    return (
        <html lang="bn">
            <body
                className={`${hindSiliguri.variable} ${poppins.variable} antialiased`}
            >
                <StoreProvider>{children}</StoreProvider>
            </body>
        </html>
    );
}
